# Generated by Django 4.2.11 on 2025-02-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_id', models.CharField(max_length=50, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='CVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.JSONField(default=dict)),
                ('education', models.JSONField(default=list)),
                ('work_experience', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_processing.cv')),
            ],
        ),
    ]
