# Generated by Django 4.2.11 on 2025-02-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv_id',
        ),
        migrations.AddField(
            model_name='cv',
            name='filename',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
